services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      - pingr.db
      - pingr.mail
      - pingr.cache
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=pingr.db;Port=5432;Database=pingr;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      ConnectionStrings__Cache: pingr.cache:6379,password=${REDIS_PASSWORD}
      Tokens__AccessToken__Secret: ${ACCESSTOKEN_SECRET}
      Email__Password: ${EMAIL_PASSWORD}
      
  pingr.db:
    container_name: "pingr.db"
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: pingr 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  pingr.mail:
    container_name: "pingr.mail"
    image: axllent/mailpit
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - 8025:8025
      - 1025:1025
    volumes:
      - ./data:/data
  
  pingr.cache:
    container_name: "pingr.cache"
    image: redis:8-alpine
    restart: always
    command: "redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: