services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      - pingr.db
      - pingr.mail
      - pingr.cache
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=pingr.db;Port=5432;Database=pingr;Username=postgres;Password=postgres
      ConnectionStrings__Cache: pingr.cache:6379,password=jTjlQ9mKFUHYbpiHYXM23HUrZyti4H3zUKrc6pdWeUP
      Tokens__AccessToken__Secret: yU16thMLT0uaBgVyDh1nU2f4ei2fxlhx3tPVnTPQPas
      Email__Password: nyQdap-vecved-1rikti
      
  pingr.db:
    container_name: "pingr.db"
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: pingr 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  pingr.mail:
    container_name: "pingr.mail"
    image: axllent/mailpit
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - 8025:8025
      - 1025:1025
    volumes:
      - ./data:/data
  
  pingr.cache:
    container_name: "pingr.cache"
    image: redis:8-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: "redis-server --requirepass jTjlQ9mKFUHYbpiHYXM23HUrZyti4H3zUKrc6pdWeUP --appendonly yes"

volumes:
  postgres_data:
  redis_data: